### ISSUE TITLE
Ti Connect

### ISSUE THREAD

**Issue by nabulator** [utz82/HoustonTracker2#15]
backing up HT2 with TiConnect on windows results in the following error:
The name of the current variable is missing. 

Using a Ti84+SE.

Edit:
File transfer works fine with Tilp2 and Tiemu on linux lol.

**Comment by utz82** [comment]
This is most likely an issue with TI-Connect, can't do much about it.
Just to be certain, could you check if you're still getting the same error with the latest beta version ( https://github.com/utz82/HoustonTracker2/blob/master/ht2.8xp?raw=true )? There was a problem with faulty checksum calculation before, but this shouldn't affect backups.
