### ISSUE TITLE
Ticks per minute to BPM?

### ISSUE THREAD

**Issue by JurianBruinink** [utz82/HoustonTracker2#19]
Awesome software! Just cant seem to set the BPM right. Lets say I want 160Beats per minute. 160/60= 2,666667 so around that many beats each second with a grid of 16th notes. The problem is that i have no clue how many ticks are in a second and I can't seem to find it anywhere. Could you please tell me?
I am aware that i need to convert the value to hexadecimal before entering it in the TI. Oh and maybe add it to the manual:) thanks!

**Comment by utz82** [comment]
Hi Jurian, unfortunately there's no clear answer to that. In theory, TIs run at 6 MHz, and one tick is 353x256=90368 cycles, which would give 6000000x60/(90368x16) = 248,98 bpm at speed 1 with a grid of 16th notes. But in reality, clock speeds vary wildly on these machines. I've measured between 5.1 and 7.2 MHz, depending on the model, and more importantly, battery state. Generally speaking, older models clock around 5.6-5.7 MHz with a full battery, while newer models clock at around 7 MHz with a full battery. Rates start to drop significantly once the battery gets to less than 60% full. There's also some fluctuation depending on which fx commands you use, but that should generally contribute less than 1% of a change. Hope that helps, and yeah, probably a good idea to add this info to the manual.

**Comment by JurianBruinink** [comment]
Fast and crystal clear reply, thanks a lot!
