### ISSUE TITLE
App crashes when audio starts to play

### ISSUE THREAD

**Issue by floppyjay** [utz82/HoustonTracker2#23]
Once the application runs, I am able to do things "normally" until audio plays, then the whole calculator freezes and the app crashes. Using a TI-84 Plus Silver Edition running 2.3, then I tried 2.2 to see if it would fix,a dn it still didn't work.

**Comment by utz82** [comment]
Sorry, I cannot reproduce the error. Could you upload a dump of the .8xp file just before the crash happens, so I can take a look?

**Comment by utz82** [comment]
Without further information, I cannot fix this.
