### ISSUE TITLE
Voyage 200

### ISSUE THREAD

**Issue by loorlab** [utz82/HoustonTracker2#24]
Hi Friends , excellent idea !

Is it possible to use it on a Voyage 200 from Texas Instruments?

Thanks !

**Comment by utz82** [comment]
No, because V200 is based on a different architecture (68000 vs Z80 in TI-82/83/83+/84+).

Perhaps not much consolation, but [qed68](https://github.com/utz82/qed68) would work on V200.

**Comment by loorlab** [comment]
@utz82 Oh my friend thanks for your clarification !
