### ISSUE TITLE
help trying to install the CrASH 1.6 shell on a TI-82?

### ISSUE THREAD

**Issue by m-r-m-s** [utz82/HoustonTracker2#32]
Hi @utz82 , I am trying to install the the CrASH 1.6 shell on a TI-82 but the `CRASH.82B` file is not visible when I select file > restore for some reason. I created an issue on the tilp repo for reference: https://github.com/debrouxl/tilp_and_gfm/issues/56

If you have any advice, it would be greatly appreciated. I realize this is not directly related to HT2 but thought you may have an idea as to why this might be happening. Thank you!

**Comment by m-r-m-s** [comment]
I was able to resolve the issue by renaming `CRASH.82B` to the following `crash.82b`

**Comment by utz82** [comment]
Thanks, glad you got it sorted out.
