### ISSUE TITLE
Exiting the program

### ISSUE THREAD

**Issue by 2awb** [utz82/HoustonTracker2#35]
I know this is probably a very stupid question, but how do I exit the program? Hitting Quit does nothing and I've had to resort to hitting every key, nothing. So removing the batteries and reinserting them it is. Sorry, I've had this same issue with other programs in the past.

**Comment by utz82** [comment]
It's [Alpha],[ON]. Check out the cheat sheet, good to have that at hand. 
https://raw.githubusercontent.com/utz82/HoustonTracker2/master/docs/houston_tracker_2-30_memo.pdf

**Comment by DiarioMental** [comment]
If you do that and still can't exit, look if the tracker is playing, that block the command and can't exit of the tracker, that happen to me x'd
