### ISSUE TITLE
Backing up

### ISSUE THREAD

**Issue by irrelevantdevices** [utz82/HoustonTracker2#38]
Hi, I know this is probably extremely basic, but just wanted to check how to do a back up. I connect to my TI-84+ through TI Connect rather than TiLP (was getting problems with it) - and it says in the manual I just save the entire program file on to my computer - is that right? I just ran out of battery and lost my work - so want to make sure I know how to back up properly before I rewrite it all!

**Comment by utz82** [comment]
Hi, yes, that's correct. The program file contains the work in progress 
tune and all the save slots.

**Comment by irrelevantdevices** [comment]
Great, thank you!
