### ISSUE TITLE
Playback position

### ISSUE THREAD

**Issue by irrelevantdevices** [utz82/HoustonTracker2#39]
Me again! Any way of starting playback from a different position? I've figured out how to change the loop position but would like to not have to wait through the first half of the song to check the last part..

**Comment by utz82** [comment]
Sure, you can use the [(-)] key for that. Beware though that this may 
not pick up all the FX settings that would normally carry over from an 
earlier playback position.

**Comment by irrelevantdevices** [comment]
Excellent! Thank you for always responding so quickly!
