### ISSUE TITLE
Playback broken on TI-83 Plus with ROM 1.13

### ISSUE THREAD

**Issue by mrglennjones** [utz82/HoustonTracker2#40]
Good day! I've just got the ht2 running on a ti-83 plus. followed the quick guide,  but I'm having a problem playing the entered sequence when pressing enter? I've been through the tutorial several times but can't seem to play anything and I've tried on 2 different devices now.Any help appreciated 

![20240206_162534.jpg](https://github.com/utz82/HoustonTracker2/assets/78789353/05f990b6-992d-4aa0-a7d7-f2ce921dc667)

**Comment by mrglennjones** [comment]
indecently when i press enter, i do hear a low tone which is toggled on/off when pressing enter.... seem like the playhead is stuck?

**Comment by mrglennjones** [comment]
https://github.com/utz82/HoustonTracker2/assets/78789353/28507a4b-c36d-4dc3-8798-1a2495e63595

**Comment by utz82** [comment]
Hard to say without further information. Did you fill all positions on the current row on the sequence screen (the main one, not this pattern screen)?

**Comment by mrglennjones** [comment]
> Hard to say without further information. Did you fill all positions on the current row on the sequence screen (the main one, not this pattern screen)?

I think its right?
![20240208_104914.jpg](https://github.com/utz82/HoustonTracker2/assets/78789353/d788447b-b999-44b2-b9c9-00a53f0208f5)

**Comment by utz82** [comment]
Yes, looks ok. Could you show the fx/drum pattern?

**Comment by mrglennjones** [comment]
> Yes, looks ok. Could you show the fx/drum pattern?

![20240208_105544.jpg](https://github.com/utz82/HoustonTracker2/assets/78789353/3c1be2b4-5beb-42ca-ac1d-f1ad0447e77c)

**Comment by utz82** [comment]
Sounds like it's stuck on the first row. Perhaps HOLD got activated by accident? Try tapping CLEAR once while playing.

**Comment by mrglennjones** [comment]
> Sounds like it's stuck on the first row. Perhaps HOLD got activated by accident? Try tapping CLEAR once while playing.

That didn't seem to resolve it but when I tapped clear again, it cleared the ram! ![20240208_110045.jpg](https://github.com/utz82/HoustonTracker2/assets/78789353/845b4891-a260-42d4-a462-0ab93986f405)

**Comment by utz82** [comment]
Ouch. That indicates that there might be a problem outside of HT2 (ie. corrupt RAM), or that HT2 got corrupted when it was copied to the calculator.

Just to be sure: You did clear the memory before installing HT2, right? Also, what is your ROM version ([2nd][MEM][1], do NOT press ENTER on the screen that pops up)?

**Comment by mrglennjones** [comment]
> Ouch. That indicates that there might be a problem outside of HT2 (ie. corrupt RAM), or that HT2 got corrupted when it was copied to the calculator.
> 
> Just to be sure: You did clear the memory before installing HT2, right? Also, what is your ROM version ([2nd][MEM][1], do NOT press ENTER on the screen that pops up)?

I'm sure I did clear it, as per the instruction, but I can try again now

The version is 1.13

**Comment by utz82** [comment]
I faintly remember someone else having issues with this exact ROM version, so that might be the culprit.
Before taking any drastic steps, could you try to install HT2 one more time, and see if the problem persists?

**Comment by mrglennjones** [comment]
i just tried a second t1-83 and same thing happened, must be a prob with the ROM version?

shall i upgrade them? i've just been given these so im a newbie, i assume i upgrade with ti connect?
________________________________

**Comment by utz82** [comment]
Does the second TI also run 1.13? In that case, yes, I'd suggest upgrading to 1.19. The .8xu is available on archive.org. Either TI-Connect or TiLP should be fine for upgrading, just don't install both at the same time.

**Comment by mrglennjones** [comment]
yes they're both identical

thanks, ill grab the new ROM and get back to you soon

________________________________

**Comment by mrglennjones** [comment]
@utz82 ok thats fixed it! i can hear the tones and drum machine. yay!

indecently rowplay mode was also broken in the older OS ROM,

**Comment by utz82** [comment]
Glad to hear it, and thanks for helping to solve the puzzle.

I will change the title of this issue, and leave it open until I get around to providing a fix for 1.13, or at least add a note to the manual.

**Comment by utz82** [comment]
Added a note to the manual. I think a full fix isn't worth it since 1.13 ROMs aren't super common in the wild, but if anybody else wants to work on one, I'd be more than happy to accept a PR.
