### ISSUE TITLE
Will this work on a TI-89?

### ISSUE THREAD

**Issue by willthemoor** [utz82/HoustonTracker2#6]
Hi,

Sorry—I know nothing of the lineage of these machines. But! Just found a TI-89 in the closet and immediate thought of Houston Tracker. Before I go sorting out how to even hook it up to my computer and wiping out the OS, thought perhaps I could just ask if you know for certain that it won't work.

Thanks!

**Comment by utz82** [comment]
Hi there,

It definately won't work with the TI-89. Despite the similar looks, the 89 is a completely different machine - different CPU, different lcd controller, etc.

However, I have plans to write a music driver for the 68k line of TI calcs (which the 89 belongs to) at some point in the not-too-distant future, so don't throw it away yet ;) This won't feature an on-calc interface like HT2 though, probably it'll be just a simple PC converter.

**Comment by willthemoor** [comment]
Sadface. Thanks very much for the reply though!
