### ISSUE TITLE
Only the first few blocks in the song save properly.

### ISSUE THREAD

**Issue by ghost** [utz82/HoustonTracker2#7]
I have been trying to save songs on my TI-84+ Silver Edition, using the "Y=" key in ALPHA mode to save to slot 0 or 1. When I save, I get "E0", which means that the save should have succeeded. However, when I load the song again with "Y=" and enter slot 1 or 0, the song loads with the patterns intact, but they are not in the song itself, which is all "--", except for the first row, on channel 1 and 2. I have not seen an error other than "E0". I am running the .8xp program with Doors CS 7.2, as suggested by the "shell" column in the TI-84+ SE row, inside the table in section 1.3 of the documentation.
My only other calculator is a TI-82, whose ROM should be compatible with CrASH, but I cannot test it as I lack a GraphLink cable.

**Comment by utz82** [comment]
Ah, bugger. Thanks for reporting, though.
A couple of questions:
- Which HT2 version are you using, 2.00 stable or the current beta?
- Do you by any chance have gaps (--) in your song matrix before saving? HT2 will discard everything after the first --.

**Comment by ghost** [comment]
If channels that I just leave as "--" count, then yes, this is just a beginner's mistake. But I am using the stable version from the site, not the later ones from git. I'm guessing this is a user problem, though, as I didn't use channel 3 in most rows.

**Comment by utz82** [comment]
Ok, mystery solved ;) My bad, I should make that more clear in the manual. You do indeed need to fill unused sequence positions in the song with empty patterns (except after the end, of course).

**Comment by utz82** [comment]
Documentation updated.
